name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Run Software tests
        run: npm run test-controller

      - name: Subir API
        run: npm start &

      - name: Esperar API estar funcionando
        run: skeep 5

      - name: Rodar os testes API via HTTP
        run: npm run test-external